name: Build LogApp

on:
  schedule:
    # Run Sunday at 6:00 AM UTC
    - cron: "0 6 * * 0"

  push:
    branches:
      - main

    paths:
    - 'Dockerfile'
    - 'Cargo.toml'
    - 'src/**'
    - '.github/workflows/build.yaml'

jobs:

  build:

    runs-on: ubuntu-20.04
    env:
      DOCKER_REPO: ghcr.io/bartr/logapp

    steps:
    - uses: actions/checkout@v2

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ env.GITHUB_ACTOR }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker pull
      run: |
        docker pull rust:latest

    - name: Docker Build
      run: |
        docker build . -t logapp
        
    - name: Docker Tag and Push
      run: |

        # tag the repo
        docker tag logapp $DOCKER_REPO:beta
        docker tag logapp $DOCKER_REPO:latest

        # Push to the repo
        docker push -a $DOCKER_REPO
