name: Build LogApp

on:
  push:
    branches:
      - main

    paths:
    - 'Dockerfile'
    - 'Cargo.toml'
    - 'src/**'

jobs:

  build:

    runs-on: ubuntu-20.04
    env:
      IMAGE: ghcr.io/bartr/logapp

    steps:
    - uses: actions/checkout@v2

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_ID }}
        password: ${{ secrets.GH_PAT }}

    - name: Docker pull
      run: |
        docker pull rust:latest

    - name: Docker Build
      run: |
        docker build . -t logapp
        
    - name: Docker Tag and Push
      run: |

        # tag the repo
        docker tag logapp $IMAGE:beta
        docker tag logapp $IMAGE:latest

        # Push to the repo
        docker push -a $IMAGE
