name: Build LogApp

on:
  schedule:
    # Run Sunday at 6:00 AM UTC
    - cron: "0 6 * * 0"

  push:
    branches:
      - main

    paths:
    - 'Dockerfile'
    - 'Cargo.toml'
    - 'src/**'
    - '.github/workflows/build.yaml'

jobs:

  build:

    runs-on: ubuntu-20.04
    env:
      BARTR: ghcr.io/bartr/logapp
      CSE_LABS: ghcr.io/cse-labs/logapp

    steps:
    - uses: actions/checkout@v2

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_ID }}
        password: ${{ secrets.GH_PAT }}

    - name: Docker pull
      run: |
        docker pull rust:latest

    - name: Docker Build
      run: |
        docker build . -t logapp
        
    - name: Docker Tag and Push
      run: |

        # tag the repo
        docker tag logapp $BARTR:beta
        docker tag logapp $BARTR:latest

        # tag the repo
        docker tag logapp $CSE_LABS:beta
        docker tag logapp $CSE_LABS:latest

        # Push to the repo
        docker push -a $BARTR

        # Push to the repo
        docker push -a $CSE_LABS
